service: sistema-pago-catalogo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    REDIS_HOST: ${ssm:/catalogo/redis/host}
    REDIS_PORT: ${ssm:/catalogo/redis/port}
    REDIS_PASSWORD: ${ssm:/catalogo/redis/password}
    S3_BUCKET_NAME: sistema-pago-catalogo-dev-catalog-csv
  vpc:
    securityGroupIds:
      - sg-0277d7759f5e00925
    subnetIds:
      - subnet-096c20ec2cdcf1c6f
      - subnet-01662b765bd74677e
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::sistema-pago-catalogo-dev-catalog-csv/*
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: ${ssm:/catalogo/kms/key}
    - Effect: Allow
      Action:
        - elasticache:Connect
      Resource: arn:aws:elasticache:us-east-1:*:replicationgroup:*

functions:
  uploadCatalog:
    handler: src/lambdas/uploadCatalog.handler
    memorySize: 512
    timeout: 60
    events:
      - http:
          path: /catalog/update
          method: post
          cors: true

  getCatalog:
    handler: src/lambdas/getCatalog.handler
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: /catalog
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript

custom:
  tsConfigPath: './tsconfig.json'
